# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AL5mGQi084iOmXh6Yecuvb604hfjOx5T
"""

# Commented out IPython magic to ensure Python compatibility.

!apt-get install -y wget > /dev/null
!rm -rf /content/cellula_task1_unified
!unzip -q cellula_task1_unified.zip -d /content/cellula_task1_unified
# %cd /content/cellula_task1_unified

!pip install -q --no-deps "requests==2.32.4"
!pip install -q --no-deps "opentelemetry-api==1.37.0" "opentelemetry-sdk==1.37.0" \
  "opentelemetry-exporter-otlp-proto-common==1.37.0" "opentelemetry-proto==1.37.0" \
  "opentelemetry-exporter-otlp-proto-http==1.37.0"

!pip install -q -r requirements.txt --upgrade --no-cache-dir
!pip install -q faiss-cpu==1.8.0.post1

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared
!chmod +x /usr/local/bin/cloudflared

import re, subprocess, time

def launch_cloudflared(port=8501):
    proc = subprocess.Popen(
        ["/usr/local/bin/cloudflared", "tunnel", "--url", f"http://localhost:{port}", "--no-autoupdate"],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
    )
    url = None
    for i in range(60):
        line = proc.stdout.readline()
        if not line:
            time.sleep(1)
            continue
        if "trycloudflare.com" in line:
            m = re.search(r"https://[^\s]*trycloudflare.com", line)
            if m:
                url = m.group(0)
                print("🌐 Public URL:", url)
                break
    if not url:
        print("❌ Failed to obtain Cloudflare URL — re-run cell if network was slow.")
    return proc, url

# Launch tunnel first
tunnel_proc, public_url = launch_cloudflared(8501)

# Launch Streamlit in background
print("🚀 Starting Streamlit...")
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"])
print("When the 🌐 Public URL appears above, click it to open your app.")